// Dynamic import for SSR compatibility - jsPDF requires browser APIs
export async function exportResultsToPDF(results, questions, answers, leadInfo = {}) {
  try {
    // Dynamically import jsPDF to avoid SSR issues
    const jsPDFModule = await import('jspdf');
    const jsPDF = jsPDFModule.default;
    const autoTable = (await import('jspdf-autotable')).default;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(0, 200, 151); // MEMA green
    doc.rect(0, 0, pageWidth, 35, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('MEMA Compliance Report', 14, 18);

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text('Financial Promotions Assessment', 14, 27);

    // Reset text color
    doc.setTextColor(0, 0, 0);

    // Client info section
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text('Report Details', 14, 48);

    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    doc.text(`Client: ${leadInfo.firm || 'Not specified'}`, 14, 56);
    doc.text(`Email: ${leadInfo.email || 'Not specified'}`, 14, 63);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`, 14, 70);

    // Score section
    const healthScore = results?.healthScore ?? 0;
    const scoreColor = healthScore >= 80 ? [16, 185, 129] : healthScore >= 60 ? [245, 158, 11] : [239, 68, 68];

    doc.setFillColor(...scoreColor);
    doc.roundedRect(140, 45, 55, 30, 3, 3, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont(undefined, 'bold');
    doc.text(`${healthScore}%`, 167, 62, { align: 'center' });
    doc.setFontSize(8);
    doc.text('Health Score', 167, 70, { align: 'center' });

    doc.setTextColor(0, 0, 0);

    // Summary stats
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text('Summary', 14, 88);

    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    const issuesCount = results?.potentialFailures?.length ?? 0;
    const totalQuestions = Object.keys(answers || {}).length;
    doc.text(`Total Questions Answered: ${totalQuestions}`, 14, 96);
    doc.text(`Issues Found: ${issuesCount}`, 14, 103);
    doc.text(`Status: ${healthScore >= 80 ? 'Strong' : healthScore >= 60 ? 'Needs Attention' : 'Critical'}`, 14, 110);

    // Questions table
    const tableData = [];
    if (Array.isArray(questions)) {
      questions.forEach((section) => {
        if (section.items) {
          section.items.forEach((item) => {
            const userAnswer = answers?.[item.id];
            let answerText = 'Not answered';
            if (userAnswer?.answer) {
              answerText = typeof userAnswer.answer === 'object'
                ? JSON.stringify(userAnswer.answer).replace(/["\[\]{}]/g, '')
                : String(userAnswer.answer);
            }
            tableData.push([
              item.questionRef || '-',
              item.questionText?.substring(0, 80) + (item.questionText?.length > 80 ? '...' : ''),
              answerText.substring(0, 30) + (answerText.length > 30 ? '...' : ''),
            ]);
          });
        }
      });
    }

    if (tableData.length > 0) {
      autoTable(doc, {
        startY: 120,
        head: [['Ref', 'Question', 'Answer']],
        body: tableData,
        theme: 'striped',
        headStyles: {
          fillColor: [0, 200, 151],
          textColor: 255,
          fontStyle: 'bold',
          fontSize: 9,
        },
        styles: {
          fontSize: 8,
          cellPadding: 3,
          overflow: 'linebreak',
        },
        columnStyles: {
          0: { cellWidth: 25 },
          1: { cellWidth: 110 },
          2: { cellWidth: 45 },
        },
        alternateRowStyles: {
          fillColor: [248, 250, 252],
        },
      });
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      doc.text(
        `Generated by MEMA Compliance | Page ${i} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    }

    doc.save(`MEMA_Compliance_Report_${Date.now()}.pdf`);
    return true;
  } catch (error) {
    console.error('PDF export error:', error);
    throw new Error('Failed to generate PDF: ' + error.message);
  }
}
